"""Initial migration

Revision ID: 9c5f7613b47c
Revises: 
Create Date: 2026-08-31 15:18:30.732420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5f7613b47c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('liquidity_tier', sa.Enum('BLUE_CHIP', 'ESTABLISHED', 'VOLATILE', 'RESTRICTED', name='liquiditytier'), nullable=False),
    sa.Column('margin_requirement', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_leverage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shortable', sa.Boolean(), nullable=True),
    sa.Column('tier_last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listed_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jwt_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('open_interest',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('total_long_shares', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_short_shares', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_captured_at'), 'portfolio_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside'), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'LIQUIDATED', name='positionstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('stock_price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('change_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_price_snapshots_captured_at'), 'stock_price_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_stock_price_snapshots_symbol'), 'stock_price_snapshots', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Enum('OPEN_LONG', 'OPEN_SHORT', 'CLOSE_LONG', 'CLOSE_SHORT', 'LIQUIDATION', name='tradeaction'), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('price_executed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash_delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_stock_price_snapshots_symbol'), table_name='stock_price_snapshots')
    op.drop_index(op.f('ix_stock_price_snapshots_captured_at'), table_name='stock_price_snapshots')
    op.drop_table('stock_price_snapshots')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_captured_at'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('open_interest')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
